### ISSUE TITLE
SP2 - HeapFile

### ISSUE THREAD

**Issue by Jancikos** [Jancikos/aus2#11]
## Todo
- [x] sekvencny vypis vsetkych blokov
- [x] delete
- [x] vyčísliť početnosti prístupov do súboru
- [x] preklopit sem generator operacii zo SP1

## Otázky
- [x] Kedy je nutné ukladať metada štruktúry do súboru?
   - po ich zmene ?
   - _len na konci_
- [x] Kedy je nutné ukladať blok do súboru?
   -  po ukončení operácie s ním ?
   - _po každou prácou s nim_
- [x] Je nutné validovať adresu, ktorá mi prichádza ako parameter?
  - je to tam vhodne pridat 
- [x] Preveriť si zložitosti operácií

**Comment by Jancikos** [comment]
### Operacia delete
čo všetko treba ošetriť?
- keď je blok **pred** operáciou
  - plný
    - ostatne čiastočne naplnený
    - no ak by bol BlockFactor == 1, tak by mohol ostať aj prázdny
  - čiastočne naplnený
    - ostatne čiastočne naplnený
    - ostane prázdny
  - prázdny
    - tak z neho nemám čo mazať...

- keď je blok **po** operácií
  - plný
    - nemôže nastať (iba ak nenastal delete)
  - čiastočne naplnený
    - zaradiť do radu čiastočne naplnených
      - iba ak tam už zaradený nie je...
  - prázdny
     - ak bol pred tym čiastočne naplne, tak ho odobrat z toho radu
     - zaradit do zoznamu prazdnych
       - pred tym v tom zozname byt nemohol, lebo obsahoval prvok...
