### ISSUE TITLE
SP2 - Checkpoint 1

### ISSUE THREAD

**Issue by Jancikos** [Jancikos/aus2#13]
### TODO
- [x] zmeniť return type GetHash() na ozaj pole bitov, nie int
- [x] pri pouzivani heapfilu v dhf prestat pouzivat stack free blokov (aj tak sa nevyuziva)
- [x] pouztitie _heapFile.CreateNewBlock(); nahradit metodou GetEmptyBlock
- [x] upravit data podla zadania
- [x] do HeapFilu pridat aj update
- [x] do generatora pridat update

#### QA
- [x] Musí byť aj štruktúra EHF celá znovunačíteľná z disku? 
  - či si aj ona musí ukladať svoje metadáta (adresár...)
  - vo výsledku musia byť uložené aj riadiace informácie
    - budúci týždeň ešte nemusia byť
    - no vo finále musí byť, kľudne v osobitnom súbore

**Comment by Jancikos** [comment]
# Notes
- v hlavnej aplikácii otvoriť tester v osobitnom okne
- POZOR - insert asi nie je okay
   - pozor na zvacsovanie adresara - mal by sa len robit tak ako som na zaciatku robil
   - _moze to takto ostat, len si musim byt naozaj isty ze spravne skacem_
   - _ide najma o to, aby som vzdy pristupoval na konkretnu adresu a nie ich prechadzal_
   - TODO - velmi nutne prekontrolovat viac vkladani za sebou 0teho elementu
- pre delete pridat do RAM aj VALID count danych heap file blokov
- nikdy z adresara neukazovat do prazdneho bloku
  - je to zbytocne, hlavne ich urcite neukladat do suboru
- do buduceho tyzdna
  - dat dokopy GUI semestralky
  - stat. hasovanie s insertom
- ak sa mi pri zvacsovani bloku ostanu vsetky data stale v jednom bloku
  - tak novy blok co som mal pripraveny ani zezapisujem
  - ten stary blok co som mal priradim k tej adrese kde ostali itemy
  - a nechavam len ten stary blok, dalsie nezapisujem
