### ISSUE TITLE
SP2 - Checkpoint 2

### ISSUE THREAD

**Issue by Jancikos** [Jancikos/aus2#15]
## Cieľ
Pre zisk 3 bodov za prvú priebežnú kontrolu je potrebné najneskôr v jedenástom týždni
predviesť:
- Aplikáciu, kde bude dôsledne oddelené jadro/model od GUI a ktorá bude umožňovať realizovať operácie 1 až 4 (nedajú sa meniť kľúčové atribúty), sekvenčný výpis všetkých súborov na GUI a naplnenie databázy generátorom z GUI.
- Pre zisk akýchkoľvek bodov je potrebné mať plne splnené požiadavky na prvú kontrolu rozpracovania a zapracované prípadné nedostatky z prvej kontroly. 

## Popis úloh
V tejto demonštračnej verzii spoločnosť požaduje, aby boli k dispozícii nasledujúce operácie:
1. Vyhľadanie všetkých evidovaných údajov o vozidle (vozidlo sa vyhľadá podľa id zákazníka
alebo podľa EČV – vyberie si užívateľ),
2. Pridanie vozidla – na základe zadaných údajov zaradí vozidlo do evidencie (pozor na ošetrenie
unikátnosti niektorých údajov),
3. Pridanie návštevy servisu - na základe zadaných údajov pridá návštevu servisu do evidencie
(vozidlo sa vyhľadá podľa id zákazníka alebo podľa EČV – vyberie si užívateľ),
4. Zmena – umožní zmeniť akékoľvek evidované údaje (vozidlo sa vyhľadá podľa id zákazníka
alebo podľa EČV – vyberie si užívateľ), pozor na zmenu kľúčových a nekľúčových atribútov

## TODO 
- [x] hromadne generovanie dat
- [x] clear backendu
- [x] vyriesit divne miznutie itemov po inserte - pozor na inicializaciu a finalne savovanie struktur
- [x] zabezpecit aby sa ulozil stav celeho zakaznika az po stlaceni tlacidla Update
- [x] POZOR na vyhladavanie podla ECV
  - problem s hešovacou funckiou 
- [x] otestovat funknost operacii
