### ISSUE TITLE
SP2 - final

### ISSUE THREAD

**Issue by Jancikos** [Jancikos/aus2#17]
## TODO
- [x] EHF - delete
- [x] EHF - update aj klucovych atributov
- [ ] dokumentacia
  - popis operacii štruktúr
  - popis jadra aplikácie

**Comment by Jancikos** [comment]
### Otestovania mazania nad EHF

- vymažem item, po vymazaní môže nastať situácia:
  - [ ] blok ostal úplne prázdny
  - [ ] v bloku ešte ostali prvky
    - skús nájsť suseda
      - [ ] sused neexistuje -> kočím
    - ak si našiel suseda 
    - skontroluj či sa vaše prvky spolu zmestia do jedného bloku
      - [ ] ak nie -> končím
    - spoj bloky
      - zníž hlbku...
    - skontroluj či netreba znížiť hlbku celého adresára
