### ISSUE TITLE
SP1 -  Checkpoint 2

### ISSUE THREAD

**Issue by Jancikos** [Jancikos/aus2#3]
- [x] Navrhnutú údajovú štruktúru
    - stačí nákres celého systému,
- [x] Naprogramované a otestované všetky operácie údajovej štruktúry vrátane bodového vyhľadávania. 
    - Funkčnosť je potrebné predviesť pomocou generátora operácii.
- Funkčnosť bodov: 1, 3, 4 v aplikácii s aspoň jednoduchým GUI.
    - [x] Vyhľadanie nehnuteľností – podľa zadanej GPS pozície sa nájdu všetky nehnuteľnosti, ktorých niektorý krajný bod sa zhoduje s vyhľadávanou GPS.
    - [x] Vyhľadanie všetkých objektov – podľa dvoch zadaných GPS pozícií (tieto definujú obdĺžnik) sa nájdu všetky evidované parcely aj nehnuteľnosti, ktorých niektorý krajný bod sa zhoduje s vyhľadávanou GPS
    - [x] Pridanie nehnuteľnosti – na základe vstupných údajov (súpisné číslo, popis, zoznam pozícií GPS ohraničujúcich nehnuteľnosť) sa pridá nehnuteľnosť do evidencie. 
        - Zoznam referencií na parcely, na ktorých stojí naplní systém automaticky.
        - Avšak pre zjednodušenie budeme nehnuteľnosť považovať za stojacu na parcele ak s ňou má spoločný aspoň jeden z dvoch bodov

---

### Todo 

- [x] pripravit 4d kd strom na testovanie
- [x] do generatora v testerovi pridat typ operacie AddDuplicate 
- [x] prekopat iteratory
- [x] vyriesit problem s pretecenim zasobnika pri generovani prvkov
- [x] po doubleclicku na seed vygenerovat novy
- [x] prerobit logged operacii, do konzoly pisal vzdy a do suburu len podla verobisty
