### ISSUE TITLE
SP1 - final

### ISSUE THREAD

**Issue by Jancikos** [Jancikos/aus2#8]
### TODO
- [x] delete bez rekurzie
- [x] prekontrolovat a vycislit si zlozitosti mojho KD stromu
   - už len doriešiť _findReplacement node
- [x] priraviť si test podľa Teamsu
- [x] komentare z obhajoby
- [x] prerobit generator parciel/nehnutelnosti
- [x] zbavit sa vsetkych TODO
- [x] dokumentacia
- [x] ukladanie do suboru

**Comment by Jancikos** [comment]
## Požiadavky na tester, podľa Teamsu
Dáta budú sekundárne kľúče X, Y - celé čísla v rozsahu 1-50 .
Primárny (unikátny) kľúč bude náhodný string v dĺžke 10 znakov.  

Najskôr sa vloží 20000 hodnôt. 
Potom sa budú náhodne vykonávať všetky podporované operácie, pričom po každej z nich sa nejakou kompletnou prehliadkou skontroluje, či je v strome rovnaký počet prvkov ako v pomocnej štruktúre.
